// Generated by CoffeeScript 1.12.7
var initMap, initialize, map, stylesArray;

map = null;

stylesArray = [
  {
    'featureType': 'water',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#e9e9e9'
      }, {
        'lightness': 17
      }
    ]
  }, {
    'featureType': 'landscape',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#f5f5f5'
      }, {
        'lightness': 20
      }
    ]
  }, {
    'featureType': 'road.highway',
    'elementType': 'geometry.fill',
    'stylers': [
      {
        'color': '#ffffff'
      }, {
        'lightness': 17
      }
    ]
  }, {
    'featureType': 'road.highway',
    'elementType': 'geometry.stroke',
    'stylers': [
      {
        'color': '#ffffff'
      }, {
        'lightness': 29
      }, {
        'weight': 0.2
      }
    ]
  }, {
    'featureType': 'road.arterial',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#ffffff'
      }, {
        'lightness': 18
      }
    ]
  }, {
    'featureType': 'road.local',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#ffffff'
      }, {
        'lightness': 16
      }
    ]
  }, {
    'featureType': 'poi',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#f5f5f5'
      }, {
        'lightness': 21
      }
    ]
  }, {
    'featureType': 'poi.park',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#dedede'
      }, {
        'lightness': 21
      }
    ]
  }, {
    'elementType': 'labels.text.stroke',
    'stylers': [
      {
        'visibility': 'on'
      }, {
        'color': '#ffffff'
      }, {
        'lightness': 16
      }
    ]
  }, {
    'elementType': 'labels.text.fill',
    'stylers': [
      {
        'saturation': 36
      }, {
        'color': '#333333'
      }, {
        'lightness': 40
      }
    ]
  }, {
    'elementType': 'labels.icon',
    'stylers': [
      {
        'visibility': 'on'
      }
    ]
  }, {
    'featureType': 'transit',
    'elementType': 'geometry',
    'stylers': [
      {
        'color': '#f2f2f2'
      }, {
        'lightness': 19
      }
    ]
  }, {
    'featureType': 'administrative',
    'elementType': 'geometry.fill',
    'stylers': [
      {
        'color': '#fefefe'
      }, {
        'lightness': 20
      }
    ]
  }, {
    'featureType': 'administrative',
    'elementType': 'geometry.stroke',
    'stylers': [
      {
        'color': '#fefefe'
      }, {
        'lightness': 17
      }, {
        'weight': 1.2
      }
    ]
  }
];

initMap = function($map) {
  var $pin1, flightPath, flightPlanCoordinates, mapOptions, marker1;
  if ($map === 'taiwan') {
    $pin1 = new google.maps.LatLng(25.049566, 121.5574183);
  } else {
    $pin1 = new google.maps.LatLng(22.2811539, 114.1817363);
  }
  mapOptions = {
    zoom: 16,
    center: $pin1,
    streetViewControl: false,
    scaleControl: true,
    scrollwheel: true,
    disableDefaultUI: true,
    draggable: true,
    zoomControlOptions: {
      position: google.maps.ControlPosition.TOP_CENTER,
      style: google.maps.ZoomControlStyle.LARGE
    },
    draggableCursor: 'crosshair'
  };
  if ($map === 'taiwan') {
    map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);
  } else {
    map = new google.maps.Map(document.getElementById('map_canvas2'), mapOptions);
  }
  map.setOptions({
    styles: stylesArray
  });
  marker1 = new google.maps.Marker({
    position: $pin1,
    title: 'Shopline',
    icon: 'assets/images/sprite/ico--location.png'
  });
  marker1.setMap(map);
  flightPlanCoordinates = [
    {
      lat: 25.053125,
      lng: 121.439582
    }, {
      lat: 25.052338,
      lng: 121.438724
    }, {
      lat: 25.056935,
      lng: 121.436010
    }, {
      lat: 25.055049,
      lng: 121.432351
    }, {
      lat: 25.054903,
      lng: 121.432448
    }
  ];
  flightPath = new google.maps.Polyline({
    path: flightPlanCoordinates,
    geodesic: true,
    strokeColor: '#2f2434',
    strokeOpacity: .3,
    strokeWeight: 4
  });
  flightPath.setMap(map);
};

initialize = function() {
  initMap('taiwan');
  initMap('hongkong');
};

$(function() {
  google.maps.event.addDomListener(window, 'load', initialize);
});
